(cgi) fixed error preventing rendering of "Missing files" list (Closes: #206)
~~~~
Traceback (most recent call last):
  File "/usr/share/moosefs-cgi/mfs.cgi", line 3817, in mcdata.sort()
TypeError: '<' not supported between instances of 'bytes' and 'str'
~~~~

Signed-off-by: Dmitry Smirnov <onlyjob@member.fsf.org>