MooseFS 3.0.61-1
 * (master) fixed lookup in case of missing chunks (lookup returned ENXIO in such case)
 * (mount) added mfstimeout option to force timeout for all I/O operations
 * (autotools) fixed problem with 'undefined reference to rpl_malloc/rpl_realloc'